# .pre-commit-config.yaml

# Define the version of pre-commit to use
default_language_version:
  python: python3.12.2  # Specify your python version

# Define the pre-commit hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0  # Use the latest tag from this repo
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
        language_version: python3

  - repo: https://github.com/psf/black
    rev: 23.1a1  # Use the latest tag from this repo
    hooks:
      - id: black
        args: [--safe]
        language_version: python3.12.2  # Specify your python version

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: python
        types: [python]
        additional_dependencies: []
        pass_filenames: false

# Optionally, you can add other hooks as needed
